[package]
name = "skydesk2"
version = "1.0.0"
description = "SkyDesk2"
authors = ["angelbests1314@live.com"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "skydesk2_lib"
crate-type = ["lib", "cdylib", "staticlib"]

[build-dependencies]
tauri-build = { version = "2.0.1", features = [] }

[dependencies]
tauri = { version = "2.0.2", features = ["protocol-asset", "tray-icon", "image-png", "image-ico", "devtools"] }
tauri-plugin-shell = "2.0.1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri-plugin-process = "2.0.1"
tauri-plugin-fs = "2.0.1"
tauri-plugin-dialog = "2.0.1"
tauri-plugin-localhost = "2.0.1"
tauri-plugin-network = "2.0.4"
tauri-plugin-system-info = "2.0.8"
tauri-plugin-clipboard-manager = "2.0.1"
tauri-plugin-http = "2"
tiny_http = "0.12.0"
xcap = "0.0.13"
windows-capture = "1.3.6"
cpal = "0.15.3"
image = "0.25.2"
lazy_static = "1.4"
png = "0.17.14"
rdev = {version = "0.5.3", features = ["unstable_grab"] }
bytemuck = "1.0"
[target."cfg(windows)".dependencies.windows]
version = "0.58.0"
features = [
    "Win32_UI_WindowsAndMessaging",
    "Win32_Foundation",
    "Win32_Graphics_Dwm",
    "Win32_Graphics_Gdi",
    "Win32_System_Com",
    "Win32_System_Registry"
]

[target."cfg(macos)".dependencies.cocoa]
version = "0.24"

[target.'cfg(not(any(target_os = "android", target_os = "ios")))'.dependencies]
tauri-plugin-autostart = "2"
tauri-plugin-global-shortcut = "2"
tauri-plugin-single-instance = "2"


