name: Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: true # 如果有新的发布任务，取消正在进行的任务

jobs:
  publish-tauri:
    permissions:
      contents: write # 授予写入仓库内容的权限
    strategy:
      fail-fast: false # 某个平台构建失败不影响其他平台
      matrix:
        include:
          - platform: "windows-latest"
            args: ""

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      # 然后设置 Node.js
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"

      - name: Install dependencies
        run: npm install

      # 安装 Rust
      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable # Set this to dtolnay/rust-toolchain@nightly
        with:
          # Those targets are only used on macos runners so it's in an `if` to slightly speed up windows and linux builds.
          targets: ${{ '' }}

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: "./src-tauri -> target"

      - name: Create release
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # 使用之前配置的私钥
          TAURI_SIGNING_PRIVATE_KEY: "dW50cnVzdGVkIGNvbW1lbnQ6IHJzaWduIGVuY3J5cHRlZCBzZWNyZXQga2V5ClJXUlRZMEl5UXFYRS91Z2tib1hMOTdWMHJOdmI4ai9YQ09qSDIvY1g1Q3dKRGxSRWFqQUFBQkFBQUFBQUFBQUFBQUlBQUFBQU1QLzV1eEpGNGlheEgyeVBkODBkOXpxUDN3NXZ5S0o2azFoRnZreG9NYWEwL3lBYzlUZ1k0Z3dYT2psWml4cTRxZTBybk9ONmQzQVZNeVBwMGpJZHV6RXRtVCtzOGthRjBDUUtJYlZvK3c2ZTNVRENncStiMzVTNkdXd2lseGhMRndPa3lEWFlWY3c9Cg=="
          # 使用之前配置的私钥密码
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: "skydesk21314"
        with:
          tagName: v__VERSION__ #这个动作会自动将\_\_VERSION\_\_替换为app version
          releaseName: "v__VERSION__"
          releaseBody: "See the assets to download and install this version."
          releaseDraft: true
          prerelease: false
          args: ${{ matrix.args }}
